source "yandex" "autogenerated_1" {
  folder_id           = var.folder_id
  source_image_family = var.source_image_family
  ssh_username        = var.ssh_username
  use_ipv4_nat        = "true"
}

build {
  sources = ["source.yandex.autogenerated_1"]

  provisioner "ansible" {
    playbook_file = "./playbook.yml"
  }

  post-processor "manifest" {
    output     = "${var.artifact_dir}/manifest.json"
    strip_path = true
    custom_data = {
      my_custom_data = "example"
    }
  }
}
