locals {
  #TODO: update with a version instead of uuid
  image_name = "${var.image_name}-${uuidv4()}"
}
source "yandex" "autogenerated_1" {
  folder_id           = var.folder_id
  source_image_family = var.source_image_family
  ssh_username        = var.ssh_username
  use_ipv4_nat        = "true"

  image_name = local.image_name
  image_family = var.image_family
}

build {
  sources = ["source.yandex.autogenerated_1"]

  provisioner "ansible" {
    playbook_file = "./playbook.yml"
  }

  post-processor "manifest" {
    output     = "${var.artifact_dir}/manifest.json"
    strip_path = true
    custom_data = {
      image_id = build.ImageID
      image_family = build.ImageFamily
      ssh_username = var.ssh_username
    }
  }
}
